# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-05 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0007_auto_20190801_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('slug', models.SlugField(help_text='The slug will be used to create the page URL, it must be unique among the other pages of the same level.', max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=400, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('price', models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0446\u0435\u043d\u0430')),
                ('vendor_code', models.CharField(blank=True, default=b'', max_length=255, verbose_name='\u0430\u0440\u0442\u0438\u043a\u0443\u043b')),
                ('description', models.TextField(blank=True, default=b'', verbose_name='\u043a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('main_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u043a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('content_1', tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u0425\u0430\u0440\u0430\u043a\u0442\u0435\u0440\u0438\u0441\u0442\u0438\u043a\u0438')),
                ('content_2', tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('produser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.Page', verbose_name='\u043f\u0440\u043e\u0438\u0437\u0432\u043e\u0434\u0438\u0442\u0435\u043b\u044c')),
            ],
            options={
                'verbose_name': '\u0442\u043e\u0432\u0430\u0440',
                'verbose_name_plural': '\u0442\u043e\u0432\u0430\u0440\u044b',
            },
        ),
        migrations.CreateModel(
            name='Root',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('title', models.CharField(max_length=400, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('long_title', models.CharField(blank=True, max_length=400, null=True, verbose_name='\u0434\u043b\u0438\u043d\u043d\u043e\u0435 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('main_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u0432 \u043d\u0430\u0447\u0430\u043b\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('bottom_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u0432 \u043a\u043e\u043d\u0446\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '\u043a\u043e\u0440\u043d\u0435\u0432\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u043a\u043e\u0440\u043d\u0435\u0432\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='Show on site')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Datetime last modified')),
                ('slug', models.SlugField(help_text='The slug will be used to create the page URL, it must be unique among the other pages of the same level.', max_length=255, unique=True, verbose_name='Slug')),
                ('title', models.CharField(max_length=400, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('description', models.TextField(blank=True, null=True, verbose_name='\u043a\u043e\u0440\u043e\u0442\u043a\u043e\u0435 \u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435')),
                ('main_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u043e\u0441\u043d\u043e\u0432\u043d\u043e\u0439 \u043a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('bottom_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u0432 \u043a\u043e\u043d\u0446\u0435 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
            ],
            options={
                'verbose_name': '\u0440\u0430\u0437\u0434\u0435\u043b',
                'verbose_name_plural': '\u0440\u0430\u0437\u0434\u0435\u043b\u044b',
            },
        ),
    ]
