# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-21 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsRoot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a')),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('main_content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442')),
                ('bottom_content', tinymce.models.HTMLField(blank=True, default=b'', verbose_name='\u043a\u043e\u043d\u0442\u0435\u043d\u0442 \u0432\u043d\u0438\u0437\u0443 \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u044b')),
            ],
            options={
                'verbose_name': '\u041a\u043e\u0440\u043d\u0435\u0432\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
                'verbose_name_plural': '\u041a\u043e\u0440\u043d\u0435\u0432\u0430\u044f \u0441\u0442\u0440\u0430\u043d\u0438\u0446\u0430',
            },
        ),
    ]
