# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-29 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('order_key', models.IntegerField(blank=True, null=True, verbose_name='\u043f\u043e\u0440\u044f\u0434\u043e\u043a')),
                ('show', models.BooleanField(default=True, verbose_name='\u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c')),
                ('text', models.CharField(max_length=255, verbose_name='\u0442\u0435\u043a\u0441\u0442')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['order_key'],
                'verbose_name': '\u0441\u0441\u044b\u043b\u043a\u0430',
                'verbose_name_plural': '\u0441\u0441\u044b\u043b\u043a\u0438',
            },
        ),
    ]
