# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-01 04:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='link',
            options={'ordering': ['order_key'], 'verbose_name': '\u043f\u0443\u043d\u043a\u0442 \u043c\u0435\u043d\u044e', 'verbose_name_plural': '\u043f\u0443\u043d\u043a\u0442\u044b \u043c\u0435\u043d\u044e \u0432 \u0441\u0430\u0439\u0434\u0431\u0430\u0440\u0435'},
        ),
    ]
