# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435')),
                ('file', models.FileField(help_text='png|jpg|mp4', upload_to=b'upload', verbose_name='\u0444\u0430\u0439\u043b')),
            ],
            options={
                'verbose_name': '\u0444\u043e\u043d\u043e\u0432\u044b\u0439 \u043c\u0435\u0434\u0438\u0430\u0444\u0430\u0439\u043b',
                'verbose_name_plural': '\u0444\u043e\u043d\u043e\u0432\u044b\u0435 \u043c\u0435\u0434\u0438\u0430\u0444\u0430\u0439\u043b\u044b',
            },
        ),
        migrations.CreateModel(
            name='HeroFileItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='\u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('herofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.HeroFile', verbose_name='\u043c\u0435\u0434\u0430\u0444\u0430\u0439\u043b')),
            ],
            options={
                'verbose_name': '\u0444\u043e\u043d\u043e\u0432\u044b\u0439 \u043c\u0435\u0434\u0438\u0430\u0444\u0430\u0439\u043b',
                'verbose_name_plural': '\u0444\u043e\u043d\u043e\u0432\u044b\u0439 \u043c\u0435\u0434\u0438\u0430\u0444\u0430\u0439\u043b',
            },
        ),
    ]
