# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herofile',
            name='default',
            field=models.BooleanField(default=False, verbose_name='\u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e'),
        ),
    ]
