# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_herofile_default'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herofile',
            name='file',
        ),
        migrations.AddField(
            model_name='herofile',
            name='image',
            field=models.FileField(default=1, help_text='png|jpg', upload_to=b'upload', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='herofile',
            name='video',
            field=models.FileField(blank=True, help_text='mp4', null=True, upload_to=b'upload', verbose_name='\u0432\u0438\u0434\u0435\u043e\u0444\u0430\u0439\u043b'),
        ),
        migrations.AlterField(
            model_name='herofile',
            name='default',
            field=models.BooleanField(default=False, verbose_name='\u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c \u043f\u043e \u0443\u043c\u043e\u043b\u0447\u0430\u043d\u0438\u044e'),
        ),
    ]
