# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-12 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190808_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='herofile',
            name='overlay_opacity',
            field=models.CharField(choices=[(b'0', b'0'), (b'0.1', b'10'), (b'0.2', b'20'), (b'0.3', b'30'), (b'0.4', b'40'), (b'0.5', b'50'), (b'0.6', b'60'), (b'0.7', b'70'), (b'0.8', b'80'), (b'0.9', b'90'), (b'1', b'100')], default=b'0.7', max_length=255, verbose_name='\u043d\u0430\u0441\u044b\u0449\u0435\u043d\u043d\u043e\u0441\u0442\u044c \u044d\u0444\u0444\u0435\u043a\u0442\u0430 \u0437\u0430\u0442\u0435\u043c\u043d\u0435\u043d\u0438\u044f'),
        ),
        migrations.AlterField(
            model_name='herofile',
            name='image',
            field=models.FileField(help_text='png, jpg', upload_to=b'upload', verbose_name='\u0438\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435'),
        ),
    ]
