# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-30 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.BooleanField(default=True, verbose_name='\u043e\u0442\u043e\u0431\u0440\u0430\u0436\u0430\u0442\u044c')),
                ('title', models.CharField(max_length=255, verbose_name='\u043d\u0430\u0438\u043c\u0435\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('email', models.EmailField(help_text='\u0414\u043b\u044f \u0440\u0430\u0441\u0441\u044b\u043b\u043a\u0438 \u0441 \u0444\u043e\u0440\u043c \u043e\u0431\u0440\u0430\u0442\u043d\u043e\u0439 \u0441\u0432\u044f\u0437\u0438', max_length=255, verbose_name='e-mail')),
            ],
            options={
                'verbose_name': '\u043f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u043f\u043e\u0434\u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u0438\u044f',
            },
        ),
    ]
