# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-30 10:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsroot',
            options={'verbose_name': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0441\u043f\u0438\u0441\u043a\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0435\u0439', 'verbose_name_plural': '\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430 \u0441\u043f\u0438\u0441\u043a\u0430 \u043d\u043e\u0432\u043e\u0441\u0442\u0435\u0439'},
        ),
    ]
